/*
 * This file is generated by jOOQ.
*/
package top.bigwave.jooqdemo;


import javax.annotation.Generated;

import top.bigwave.jooqdemo.tables.Author;


/**
 * Convenience access to all tables in library
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>library.author</code>.
     */
    public static final Author AUTHOR = top.bigwave.jooqdemo.tables.Author.AUTHOR;
}
